services:
    agit.contactform.endpoint.plugins:
        private: true
        class: ApiPluginListener
        factory_service:  agit.api.endpoint.listener.factory
        factory_method:   create
        arguments: [ contactform.v1, AgitContactFormBundle:Api:v1:Endpoint ]
        tags: [{ name: kernel.event_listener, event: agit.api.endpoint, method: onRegistration }]
    agit.contactform.object.plugins:
        private: true
        class: ApiPluginListener
        factory_service:  agit.api.object.listener.factory
        factory_method:   create
        arguments: [ contactform.v1, AgitContactFormBundle:Api:v1:Object ]
        tags: [{ name: kernel.event_listener, event: agit.api.object, method: onRegistration }]
